### PR TITLE
Update fedora.sh

### PR DESCRIPTION
**Pull request by joeking82**
Schedtool is needed to compile

### CODE REVIEW

**Comment by MSF-Jarvis** [comment]
Is it? I was under the impression it's only used by Lineage in their `mka` thing which was deprecated on P anyway

**Comment by joeking82** [comment]
I tried compiling a few roms and it ask for it especially du

**Comment by MSF-Jarvis** [comment]
> I tried compiling a few roms and it ask for it especially du

Using what build command? Does using `make` in place of `mka` still need it?

**Comment by joeking82** [comment]
Brunch

**Comment by joeking82** [comment]
Make needs it to

**Comment by MSF-Jarvis** [comment]
Weird. Alright then.

**Pull request merged**
