### PR TITLE
Polish stuff a bit more

### PR DESCRIPTION
**Pull request by GitNoob987**
Add a bit of polish and make it a bit more "streamlined" :P

### CODE REVIEW

**Comment by GitNoob987** [comment]
Why tho? XD

**Comment by msfjarvis** [comment]
Because I don't want the other changes...

**Comment by GitNoob987** [comment]
Like what changes?

**Comment by msfjarvis** [comment]
Have you looked at what you've PR'd? Can you tell my commit and your changes apart?

**Comment by GitNoob987** [comment]
LOL i didn't. Sorry

**Comment by GitNoob987** [comment]
BTW,come up with something better than android_build_env tho.It sounds more "universal" than it should lol

**Pull request closed without merging**
