### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by anayw2001**
this is for fedora 26 android build environment setup

### CODE REVIEW

**Comment by akhilnarang** [comment]
Cleanup and keep it similar to the other scripts please
Just one sudo dnf install, split into multiple lines with \
Check the versions of make/ninja/ccache it can install, if they're old then grab the prebuilts from the utils folder like the other scripts

**Comment by akhilnarang** [comment]
@anayw2001 can you rebase and squash them, and confirm it works, will merge then!

**Comment by anayw2001** [comment]
Script should be ready to go, but will check tonight to confirm.

**Comment by akhilnarang** [comment]
e8ed743062c087a58b92907d77354f6abf1b9367

**Pull request closed without merging**
