### PR TITLE
Setup: remove make tarball after extracting

### PR DESCRIPTION
**Pull request by frap130**
Signed-off-by: Yuvraj Saxena <thefrap130@gmail.com>

### CODE REVIEW

**Comment by frap130** [comment]
screenshot_termux_20180622-142747

**Comment by frap130** [comment]
@akhilnarang what about this?

**Comment by akhilnarang** [comment]
Patience.

**Comment by akhilnarang** [comment]
278364b288c2682808ea778d2825b1e83fc39a07

**Pull request closed without merging**
