### PR TITLE
 the "android" command is outdated, instead use sdkmanager.

### PR DESCRIPTION
**Pull request by krypticallusion**
Signed-off-by: krypticallusion <krypticallusion@gmail.com>

### CODE REVIEW

**Comment by dragonGR** [comment]
very cool

**Comment by dragonGR** [comment]
@akhilnarang bc merge it

**Comment by akhilnarang** [comment]
@dragonGR works fine?

**Comment by dragonGR** [comment]
@akhilnarang yes used it, works perfectly.

**Comment by akhilnarang** [comment]
c0b943e4e965dfe62073d8fb3bdc50525801efb7

**Pull request closed without merging**
