### PR TITLE
scripts: android_build: Symlinking python2 for python in Ubuntu 20.04

### PR DESCRIPTION
**Pull request by goodmeow**

### CODE REVIEW

**Comment by akhilnarang** [comment]
I think I have a simpler way, I'll try that otherwise will merge this

**Comment by goodmeow** [comment]
yah sure, maybe you'll find out more.

**Comment by akhilnarang** [comment]
Should be fine with 70485d2cd4933fa60a26cfbd8784f98c4489d2f4

**Comment by rickyramdani** [comment]
help me make a script to clone Facebook social media using my github address ... teach me how to make it and give an example tutorial

**Pull request closed without merging**
